### PR TITLE
Fixed 'Add tags'. Added 'Edit tags'

### PR DESCRIPTION
**Pull request by Theodorson**

### CODE REVIEW

**Comment by alexandermeindl** [comment]
I'll not except this PR, because other code is overwritten, which changed in the last weeks. Also why do you think you can change the release version?

**Comment by Theodorson** [comment]
Hi @alexandermeindl,

I've fixed linter and tests. Could you please trigger another build ?

**Comment by Theodorson** [comment]
Hi @alexandermeindl ,

Could you please trigger another build ?  A problem still exists ?

**Comment by alexandermeindl** [comment]
Hi @Theodorson,

thanks for you contribution, it is now merged to main branch!

**Comment by alexandermeindl** [comment]
Hii @Theodorson,
I found a bug with your pr: no journal entries are created in issues, if you add tags. Can you provide a fix for it in a new pr?

**Comment by Theodorson** [comment]
Hi @alexandermeindl
I understand add tags is not doing the same with the save tags from issue page right ? I've tested with a older branch without my changes and also doesn't works. I'm not sure is a bug from my PR. I would like to repair/add this behavior what should exists.
image
image

**Comment by alexandermeindl** [comment]
Hi @Theodorson,
this would be great!

Journal for tags is tricky, I spent some hours, days for it on other actions (edit form, tag edit on show, creating new issues, deleting tags,...). It was not easy to find a solution, which worked for all this actions. Maybe you are right, that adding tags on context-menu never worked with journal entries.

It would be really great if you have time for it and can find a solution.

**Comment by Theodorson** [comment]
Hi @alexandermeindl,

Happy new year!

I was in holiday. I will try to add this feature when I will have some free time, I spoke with a colleague and I think we found a solution. I will come back with news about it.

**Pull request merged**
