### PR TITLE
fix saved queries after migrate from redmineup_tags

### PR DESCRIPTION
**Pull request by rkteam**
fix for  #52

### CODE REVIEW

**Comment by alexandermeindl** [comment]
Hi @rkteam,

can use change your PR, that only IssueQuery is used - and not all subclasses of Query? We use `issue_tags` for non-issue-queries, which is in conflict with your change.
Maybe `AgileQuery` and `AgileChartsQuery` would be another queries, you want to migration (if you use redmine_agile).

**Comment by rkteam** [comment]
Hi

We use another Query, not only IssueQuery & AgileQuery, thats why i added subclasses of Query. I assumed that other users would also want to fix not only IssueQuery. While doing this I ran into a problem on our production -  if there are records of subclasses Query exist in the table, but plugins have already been removed. I fixed this.

How can i reproduce the conflict with issue_tags?

Is the plugin in which the conflict occurs paid?

**Comment by alexandermeindl** [comment]
> Hi
> 
> We use another Query, not only IssueQuery & AgileQuery, thats why i added subclasses of Query. I assumed that other users would also want to fix not only IssueQuery. While doing this I ran into a problem on our production - if there are records of subclasses Query exist in the table, but plugins have already been removed. I fixed this.
> 
> How can i reproduce the conflict with issue_tags?
You can't.
> 
> Is the plugin in which the conflict occurs paid?
Yes. We use additional_tags as base of our plugins. If an entity is not issue and has a relation to issues, there are `issue_tags` for it.

Independently of that, I would prefer a whitelist solution for it (with defined classes), because other plugins can also use `issue_tags `- nobody known.

**Comment by alexandermeindl** [comment]
I close it, because no solution was provided by a static list of classes.

**Pull request closed without merging**
